<a href="https://colab.research.google.com/github/Soham2020/Collaborative-RS/blob/main/Collaborative_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

plt.style.use("ggplot")

import sklearn
from sklearn.decomposition import TruncatedSVD
from google.colab import files
uploaded=files.upload()
S_Mart_ratings = pd.read_csv('data.csv',encoding='1252')
S_Mart_ratings = S_Mart_ratings.dropna()
S_Mart_ratings.head()

Saving data.csv to data (1).csv

        userId                 productId             title   price  rating
0  215p6515544  61d817667baf287c6577d593  Apple i-Phone 13  165000       5
1  715q6515545  61d81a94565b8885ed727a48       Apple i-Pad  115000       2
2  119q1515547  61d94fe05be5b22430c46852      Samsung M31s  115000       4
3  215f6515548  61dad0f2bd0376ae20bb8263  Apple i-phone 11   14500       3
4  215f6515548  61dad0f2bd0376ae20bb8262     Men's Tshirts     500       5

In [ ]:
S_Mart_ratings.shape

(11, 5)

In [ ]:
S_Mart_ratings_new = S_Mart_ratings.head(10000)

In [ ]:
#Utility Matrix
ratings_utility_matrix = S_Mart_ratings_new.pivot_table(values='rating', index='userId', columns='productId', fill_value=0)
ratings_utility_matrix.head()

productId,61d817667baf287c6577d593,61d81a94565b8885ed727a48,61d94fe05be5b22430c46852,61dad0f2bd0376ae20bb8225,61dad0f2bd0376ae20bb825632,61dad0f2bd0376ae20bb8261,61dad0f2bd0376ae20bb8262,61dad0f2bd0376ae20bb8263,61dad0f2bd0376ae20bb8266,61dad0f2bd0376ae20bb82as5,61dad0f2bd0376ae20bb85642
userId,,,,,,,,,,,
119q1515547,0,0,4,0,0,0,0,0,0,0,0
215f6515510,0,0,0,1,0,0,0,0,0,0,0
215f6515525,0,0,0,0,0,0,0,0,2,0,0
215f6515548,0,0,0,0,0,0,5,3,0,0,0
215f6515557,0,0,0,0,5,0,0,0,0,0,0

In [ ]:
ratings_utility_matrix.shape

(10, 11)

In [ ]:
#Transposing
temp = ratings_utility_matrix.T
temp.head()

userId,119q1515547,215f6515510,215f6515525,215f6515548,215f6515557,215f6515569,215f6515584,215f6515596,215p6515544,715q6515545
productId,,,,,,,,,,
61d817667baf287c6577d593,0,0,0,0,0,0,0,0,5,0
61d81a94565b8885ed727a48,0,0,0,0,0,0,0,0,0,2
61d94fe05be5b22430c46852,4,0,0,0,0,0,0,0,0,0
61dad0f2bd0376ae20bb8225,0,1,0,0,0,0,0,0,0,0
61dad0f2bd0376ae20bb825632,0,0,0,0,5,0,0,0,0,0

In [ ]:
#Decomposing of Matrix
SVD = TruncatedSVD(n_components=8)
decomposed_matrix = SVD.fit_transform(temp)
decomposed_matrix.shape

(11, 8)

In [ ]:
#Correlation Matrix
correlation_matrix = np.corrcoef(decomposed_matrix)
correlation_matrix.shape

(11, 11)

In [ ]:
# Randomly selection product id '61dad0f2bd0376ae20bb8261' from correlation matrix
temp.index[3]

'61dad0f2bd0376ae20bb8225'

In [ ]:
chosen = temp.index[3]

product_names = list(temp.index)
product_ID = product_names.index(chosen)
product_ID

3

In [ ]:
correlation_product_ID = correlation_matrix[product_ID]
correlation_product_ID.shape

(11,)

In [ ]:
# Recommending top 2 highly correlated products for product '61dad0f2bd0376ae20bb8225'
Recommend = list(temp.index[correlation_product_ID > 0.40])

Recommend.remove(chosen) 

S_Mart_ratings_new.loc[S_Mart_ratings_new['productId']==Recommend[1]][['title','price']]

           title  price
9  Casual Shirts    825

In [ ]:
S_Mart_ratings_new.loc[S_Mart_ratings_new['productId']==Recommend[0]][['title','price']]

          title  price
10  Men's Jeans    920